### ISSUE TITLE
Issue with installing mobile provision

### ISSUE THREAD

**Issue by stigi** [bitstadium/HockeyKit#11]
Hello,

I had to do the following change to get the mobile provision installing on the device.
This is like a quick fix. I think the real problem lies inside the main.php, but I'm not that fluent in PHP so I was glad that I somehow got it working.
https://gist.github.com/703193

The problem might have to do something with my setup. I moved the include folder to ../../includes/hockey. Maybe that caused the issue?..

Thanks
Ullrich

**Comment by DerAndereAndi** [comment]
Hi Ullrich, someone else suggested the same change and I commited it a few hours ago already. It seems to be related to some hosting services and web service environments. This change makes sure the binary/download headers are sent for this file so the iPhone does actually download and install the file instead of showing it.
- Andreas
