### ISSUE TITLE
checkUpdateAvailable_ compares wrong values

### ISSUE THREAD

**Issue by dunamis1974** [bitstadium/HockeyKit#110]
First,. thank you for the great software :)
I have current issue:
It appears that the method checkUpdateAvailable_ in BWHockeyManager.m compares the wrong values.
self.app.version - contains the App version from the server
self.currentAppVersion - contains the build

This is because on line 355 in the same file:
currentAppVersion_ = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleVersion"];

and it should be something like: 
currentAppVersion_ = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleShortVersionString"];

Kind Regards

**Comment by DerAndereAndi** [comment]
Hi,

no, the code is correct. As the documentation points out, you should make sure, the plist manifest file contains the correct build number, since it wrongly exports the CFBundleShortVersionString. As per Apples documentation, CFBundleShortVersionString is optional and CFBundleVersion is mandatory. Hence the version number/string to check for comparison is CFBundleVersion.

Best,
Andreas
