### ISSUE TITLE
authtype forcing multiple password checks

### ISSUE THREAD

**Issue by jriker1** [bitstadium/HockeyKit#119]
When I use basic authtype in my root .htaccess file to force a password on the main site, I get the credential check and then I see the main page.  Problem is after I click on an app to install it in my iPad with 5.0.1, I get two more authentication challenges, then puts an icon on my iPad desktop to start installing.  Then get two more auth challenges and then after success on all that it installs.  Am I missing something?  I can force the authentication on the root index.php only, however that's kind of a false sense of security when the actual IPA's would be wide open for download by anyone with the right URL.

JR

**Comment by DerAndereAndi** [comment]
iOS does not "cache" the authentication for a session, which results in each request requiring another auth. So this is for the .plist file, the .png file and the .ipa file in addition to the page request. Since this is all handled by iOS, the only way is to exclude everything from auth than the .ipa file.

Can't help you on that, since that highly depends on the browser. You somehow have to limit auth to those files only.

**Comment by jriker1** [comment]
According to my unix admin, the issue is actually that when you go to download the plist file the URL being passed is including the port at the end of it.  So if my URL is http://www.test.com, it is passing http://www.test.com:80 which is enough to cause Apache to challenge again.  I see this when I click on my iPad to download an app and the challenge box comes up.  The initial challenge is just "http://www.test.com", the second when I click on the plist file button is "http://www.test.com:80".  he believes if the :80 was not there it would not do this.  I am down to just the one additional challenge per app now.  I saw some references in the router.php file to port 80 but not sure if it's there or somewhere else it's being appended.

Thanks.

**Comment by DerAndereAndi** [comment]
According to the code and my test installation, the port number 80 is never added by the code. Since those lines explicitly tell to add the port address to the `baseURL` only if it differs from the default port, which is 80.

```
    $protocol = 'http';
    $default_port = 80;
    if (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on')
    {
        $protocol = 'https';
        $default_port = 443;
    }
    $this->baseURL = sprintf(
        '%s://%s%s%s/',
        $protocol,
        $_SERVER['SERVER_NAME'],
        $_SERVER['SERVER_PORT'] != $default_port ? ':'.$_SERVER['SERVER_PORT'] : '',
        $path
    );
```

Testing the process also again on my test installation, the port was never added, not to download the plist or to any URL inside the plist. So to me it rather looks like on your server setup, maybe in combination with the auth settings, the port gets added. The code does not do that.

You can validate that yourself by setting the browser to act as iPhone (Safari in the Developer menu once that is activated) and then examine the URLs and call them manually to dig in deeper.

Here are the URLs from my test installation:

Install Page: `http://alpha.buzzworks.de/`
iTMS-Download Link: `itms-services://?action=download-manifest&url=http%3A%2F%2Falpha.buzzworks.de%2Fapi%2F2%2Fapps%2Fde.buzzworks.WorldViewBeta%3Fformat%3Dplist`
Resolves into Plist download link: `http://alpha.buzzworks.de/api/2/apps/de.buzzworks.WorldViewBeta?format=plist`

Nowhere added port 80 to the URL found.

**Comment by jriker1** [comment]
OK I'm looking into this further but for now have created a PHP based wrapper to secure my site.  Challenge is right now HockeyKit assumes the ipas are in folders off the root of the web server when you click on the download button.  Other issue is the "index.php" is now two folder levels deep and not at the root anymore.  If I put my ipa and manifest files in the same two levels deep folder as the index.php file the references to the apps show on the screen, however HockeyKit is still assuming the actual ipa or manifest are at the root level and can't find it.  Is there a way to define where the IPA/Manifest files are located if they are somewhere other than in the same folder as the index.php so it can find them?  So the index.php is two folder levels deep from the htdocs  folder, and the apps are in a folder called "Apps" (and subfolders in there), right off the root of the htdocs folder.  Or that's how I would like it to work.  I can put the apps in the root of the htdocs folder however because the index.php is two levels deep it doesn't find it.

Example:
- htdocs
  - application
    - views

So the HockeyKit index.php goes in the views folder and technically from history the apps themselves go into individual folders under htdocs.

**Comment by DerAndereAndi** [comment]
Hi,

the SDK does not assume the IPA is in a subfolder of root, it assumes it is in the same folder as the plist etc. I have no clue what you are actually doing and have a hard time following what you are talking about without making lots of assumptions.

The required folder structure is documented here: https://github.com/TheRealKerni/HockeyKit/wiki/Server

HockeyKit Root: index.php
--  Subfolder: directories with bundle idenfitier naming
---- Files for the app
---- Subfolder: directories with version numbers:
------ Actual files for each version

If required files are not present in a directory level, it is ignored. You should be able to find out which files these are in the source code and change it to search in other folders of your liking.

Sorry, but I sadly have no time available to do any refactoring or changes other than bug fixes. And I don't see a bug right now.

Andreas

**Comment by jriker1** [comment]
Understood, so if the view was from a folder perspective:

--htdocs
---app1
---app2
------application
-----------views
---------------index.php

Any thoughts on how I would tell the index.php to find the app1 and app 2 folders two levels up?  Where ever the app assumes the files are (right under index.php), there must be a place I can go to tell it that the files are two levels up.

Thanks.

**Comment by DerAndereAndi** [comment]
Here https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/includes/main.php#L299
and here for version specific subfolders: https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/includes/main.php#L340

**Comment by jriker1** [comment]
Thanks for the pointers.  I was able to complete my goal with 5 or 6 strategic variable changes in the index.php (not what I call it anymore), some variable additions in the config.php and using one of the variables in config.php to override $options['appDirectory'].
