### ISSUE TITLE
iOS package as own git repo?

### ISSUE THREAD

**Issue by bryanrahn** [bitstadium/HockeyKit#121]
This would be great for doing simple pull requests versus manually copying files over.

**Comment by DerAndereAndi** [comment]
We are working on a unified version together with QuincyKit where you will be able to do that: https://github.com/codenauts/HockeySDK-iOS

**Comment by zbowling** [comment]
what is the state of the unified SDK?

**Comment by DerAndereAndi** [comment]
It is ready to be used since a while, we are doing releases as for the others and I am using it in my own apps already. We just haven't got around writing a full documentation on how to integrate it with the different ways to do that.

I am currently using it via a git submodule and added the Xcode project as a subproject to my apps.
