### ISSUE TITLE
Unable to Download Application

### ISSUE THREAD

**Issue by nyanev** [bitstadium/HockeyKit#140]
I've installed HockeyKit on my mac. Create one application. When I open safari on iPad and tap on "Install App" button, the app start downloading but at the end  of the installation I have this alert: "Unable to Download Application "App" could not be installed at this time". I can't find the solution

**Comment by dilonge** [comment]
I have the same problem with IIS server. Any onw could help us?

**Comment by brunodoamaral** [comment]
I had the same problem. In my case, it was caused by a misconfiguration on module <b>mod_rewrite</b> of Apache (which was not activated).
To check if it is your case, access your /public URL inside your browser and click on the "Download Profile" button. If it works, so your mod_rewrite may be working. If not, (ie, the URL /public/api/2/apps/com.company.myapp?format=mobileprovision goes to a 404 page), then you should fix your mod_rewrite.
http://net.tutsplus.com/tutorials/other/a-deeper-look-at-mod_rewrite-for-apache/#enabling_mod_rewrite_in_the_server

**Comment by FabianFrank** [comment]
This can also happen if the iOS version of your phone is older than the required version by the app. It can also happen if you use HTTPS and there is a certificate error. Unfortunately iOS is not good at giving a meaningful error message. Best way to test this is to open the site in Chrome with a fake iOS user agent and then try to download the plist and copy/paste the URL from the plist to the ipa and download the ipa. If all that works, your phone should be good.
