### ISSUE TITLE
Custom URL Schemes not registering properly when Installing Apps on iOS

### ISSUE THREAD

**Issue by cscott530** [bitstadium/HockeyKit#143]
Short: When installing an app through Hockey Kit, the custom URL schemes that the App supports are not being registered properly. So `[[UIApplication sharedApplication] canOpenURL:]` is returning `NO` when it shouldn't.

Long: I created a custom scheme for each of my apps in order to check whether they're missing, needing update, or the newest version.  When I install through XCode or iPhone Configuration Utility, these custom schemes work properly, and I can bounce from my app store app over to the target app.
I thought maybe it was a general OTA issue, but we also parter with Good (http://www1.good.com/), who provides their own app store app, and when we deployed through there, my custom URL schemes _did_ work.

**Comment by DerAndereAndi** [comment]
Hello,

I don't see how this could have anything to do with HockeyKit.
- The SDK does nothing that has any relation to URL schemes (check the source)
- The installation process is completely handled by iOS, all any OTA server does is passing over an URL to the ipa file that you create yourself. No OTA server can possibly touch your ipa file without breaking installation since the signing would be broken

So the problem for your code not working lies somewhere else. Maybe a bug in your code?

Anyway, again, this is nothing either the SDK or any OTA server can possibly be related to.

**Comment by cscott530** [comment]
I always try to blame someone else as a last resort, but the fact that it works OTA with another distributor, and not through a server running HockeyKit is why I came here. I honestly assumed it was a bug in Apple's OTA install logic until I tried it through Good's app distribution service.

Thanks for the quick reply, I will keep digging around for a solution.

**Comment by cscott530** [comment]
I have no idea what changed (nothing...), but it just started working. I feel like a massive tool right now. Sorry for wasting your time, hah.
