### ISSUE TITLE
hockeykit API

### ISSUE THREAD

**Issue by stevesteven** [bitstadium/HockeyKit#161]
Hi,

Is there an API for hockey kit in order to customize the server ?

**Comment by FabianFrank** [comment]
You mean to upload new versions of applications, and so on?

**Comment by stevesteven** [comment]
yeah i want to print out on the web page all apps and their versions with a web page with download link for each one and the possibility to add news versions

**Comment by FabianFrank** [comment]
I've created such an API, but it's not pretty. The issue is that you need a few dependencies:
1. PHP zip to unzip apk/ipa files
2. a) AXMLPrinter2 to parse binary android manfiests
    b) libplist to parse binary apple plists
to do inspection of the apps that are being uploaded and so on.It didn't feel right to make HockeyKit dependent on software packages like these, which are not that common / widely available. Maybe I can provide the API as an isolated/optional piece of code in the future.

**Comment by stevesteven** [comment]
i finally did what i wanted thank you for the response
