### ISSUE TITLE
After upgrade to the ios 7.1,click "Download Application" shows Cannot install applications because the certificate for xxx.domainname.com is not valid.

### ISSUE THREAD

**Issue by kamui0523** [bitstadium/HockeyKit#168]
As I know,I should change the url from http to https,but when I do this stuff in ./server/php/includes/router.php,all the css,pic file lost,and shows SSL ERROR on the page。Would help me to find it out please?Thank you.

**Comment by FabianFrank** [comment]
Is your server reachable via https otherwise? Like say, can you visit "https://yoursite.com/hockey/"? You shouldn't have to change router.php, just access your site with an https URL.

**Comment by kamui0523** [comment]
http://testflight.moregg.lab/hockey was OK
https://testflight.moregg.lab/hockey shows error as below.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Not Found
The requested URL /hockey was not found on this server.

Apache/2.2.3 (Red Hat) Server at testflight.moregg.lab Port 443
++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by FabianFrank** [comment]
This means your apache server is not correctly configured to serve hockey over https. You will have to replicate the config you made for http to also work with the https host.

**Comment by kamui0523** [comment]
Frank,thank you very much,now I have done for apache and https://testflight.moregg.lab/hockey  shows OK。But when  I check the url of "Download Application",it still shows
http://testflight.moregg.lab/camera.ios.multiple/Camera1.0.20131120/app.ipa
notice that is http,not https,although I access it from https://testflight.moregg.lab/hockey....

**Comment by FabianFrank** [comment]
Odd. Did you modify router.php or not?

FWIW I think there is a bug in https://github.com/TheRealKerni/HockeyKit/blob/develop/server/php/includes/router.php#L102. If you look at the if condition, it tests for

``` PHP
strtolower($_SERVER['HTTPS']) == 'on'
```

but the PHP docs at http://www.php.net/manual/en/reserved.variables.server.php actually state

> Set to a non-empty value if the script was queried through the HTTPS protocol.

Let me test that locally before pushing a fix.

**Comment by FabianFrank** [comment]
`$_SERVER["HTTPS"]` is indead `on` for me locally. Would you mind sharing what value it is for you?

**Comment by tfonfara** [comment]
Hi, I can confirm the "Cannot install application because the certificate for xxx.domainname.com is not valid" without SSL problem. But if you enable SSL a "Connection failed" error occurs.  On my server https is enabled, I access the page via https://... and `$_SERVER["HTTPS"]` returns `on`. With iOS 7.0 everything works as expected.

**Comment by FabianFrank** [comment]
Can you open hockey in the browser without confirming any security exception? If not, then the download of the app fails.

**Comment by tfonfara** [comment]
The used certificate is self-signed, it shows a security warning. Is there no possibility to use this with a self-signed certificate?

**Comment by FabianFrank** [comment]
In a browser the self signed cert works, because the browser handles the security exception and allows you to confirm it and continue. However, the app (.plist and .ipa) is not downloaded by the browser, it's downloaded by the system. The system does not handle the security exception and simply aborts the download. Unfortunately, there is no known way (at least to me) to get around that - unless you are willing to get a certificate that is trusted by the system. One way to do this is to pay a trusted CA (like VeriSign) for one. Another way is to import your CA that you used to self-sign to your iOS device. I haven't tested this route myself, but it should work. There are a lot of how to guides on the web that explain this:
http://blog.httpwatch.com/2013/12/12/five-tips-for-using-self-signed-ssl-certificates-with-ios/

**Comment by tfonfara** [comment]
Thanks, that helped a lot!

**Comment by FabianFrank** [comment]
I'm glad it helps. @kamui0523 let us know if we can close the issue.

**Comment by kamui0523** [comment]
Well,actually the browser works now but not at the ios device.So as your opinion I have to get a trusted CA file to solve this problem?

**Comment by FabianFrank** [comment]
As described above, you need to make sure the certificate is trusted by the phone or the download will fail.

**Comment by kamui0523** [comment]
OK,GOT IT,THANK YOU VERY MUCH!
