### ISSUE TITLE
Could not connect to "ip address" error in ios9.1

### ISSUE THREAD

**Issue by smita5** [bitstadium/HockeyKit#186]
we are trying to setup an Appstore in our workspace using hockey kit latest version.
Following things are done:
1.we have setup the wamp server on a windows system and when we try invoking the address:
   "ip-address" / "applicationname" / public 
2.Then we are able to see our listed applications (both android and ios) and we are also able to    download both ipa and apk files from above link.
3.Then we checked on an Android phone and there also it seems to work fine but when we are trying         to download files from iphone 6(ios 9.1) it is showing "could not connect to 160.110.68.199"
    any suggestions on what would have went wrong  and how to proceed

**Comment by fuacici** [comment]
same problem too

**Comment by dashart-ke** [comment]
Hi,
I had similar issues, but I solved it:
- Replace the IP by a domain (local dns needed).
- Add a valid SSL certificate for your domain.
- Change all given URLs to https

Background:
With iOS 9 all app URIs for app development / adhoc distribution has to use HTTPS, otherwise the installation will stop with strange errors like: could not resolve / found / load / install.

**Comment by saggymac** [comment]
@gdav I have the URLs setup as https using a self signed cert. But I'm still getting cannot connect errors. Hard to debug. Connection never makes it to server side access logs / error logs. Have you seen anything that suggests self signed certs won't work either (I did install the cert profile on device; so it should be trusted).
