### ISSUE TITLE
Update check fails if version string contains a space

### ISSUE THREAD

**Issue by kaptinkirk** [bitstadium/HockeyKit#21]
I just recently updated to the version of Hockey that includes stats, and I noticed that if your apps version number contains spaces while sending app data, it will fail.

A quick enough fix is to escape the parameter:

```
    [parameter stringByAddingPercentEscapesUsingEncoding:NSUTF8StringEncoding]
```

**Comment by DerAndereAndi** [comment]
Thanks, I changed it for each verison parameter, not for the whole string. I wouldn't add spaces to version string anyway ;)

Instead of "1.4 Beta 2" I suggest using continuing build numbers and put the "1.4" string into CFBundleShortVersionString. This can be automated and you never have to adjust those strings when sending them out.

**Comment by kaptinkirk** [comment]
Thanks, I did exactly that afterwards and removed the space.
