### ISSUE TITLE
Support for Xcode4 xcarchive format

### ISSUE THREAD

**Issue by stigi** [bitstadium/HockeyKit#37]
Hello,

Since Xcode 4 is golden master now it would be nice to support it's xcarchive format.
Did you already have a look into it?

Best,
Ullrich

**Comment by DerAndereAndi** [comment]
Hi Ulrich,

Xcode 4 is still under NDA. Also, what do you mean by support for xcarchive format? This format is only for local archiving, not for distributing apps. If you get such a file but expect an .ipa file, I suggest to check the dev forums for hints how to fix that.
- Andreas

**Comment by stigi** [comment]
I see you're looking into this already.
I'll check the dev forums on how to do enterprise distribution in Xcode 4. Maybe it's already working.

Thanks
Ullrich

**Comment by jaltek** [comment]
Enterprise distribution works for me in Xcode 4 the same way as in Xcode 3.
The only difference is in choosing the ".ipa" file during the "Share" process and tick the "Save for Enterprise Distribution" checkbox within the "Save As" window, in order to enter the needed details like "Application URL" etc.

**Comment by DerAndereAndi** [comment]
This has a bug though, since it does not include the CFBundleVersion value into the manifest plist file, and only integrates CFBundleShortVersionString. So make sure to have CFBundleShortVersionString present in your info.plist file for now.
