### ISSUE TITLE
Empty line in config.php cause script to generate wrong files

### ISSUE THREAD

**Issue by rbugajewski** [bitstadium/HockeyKit#44]
Adding an empty line to the config.php at the end of the file causes Hockey to include an empty line at the beginning of each file it generates (IPA, provisioning profile, manifest).

Empty lines at end of files are an UNIX standard. Despite that the corresponding function should ignore empty lines.

**Comment by DerAndereAndi** [comment]
This is PHP, so this rule cannot be applied here.

Either activate PHP output_buffering or simply don't add any characters or empty lines behind ?>

This is not a bug of this software, this is standard PHP behavior.

**Comment by DerAndereAndi** [comment]
This commit makes sure the issue won't happen any more: https://github.com/TheRealKerni/HockeyKit/commit/63743419aa7cefd40928c570b853c30db443b15f

The previous commit https://github.com/TheRealKerni/HockeyKit/commit/ac888c8f036c535b547058b633d1034151980ad9 already changed the download for the app packages to be send directly by providing the file link, instead of passing them via the API
