### ISSUE TITLE
HockeyKit + AppStore

### ISSUE THREAD

**Issue by vguerci** [bitstadium/HockeyKit#49]
Hi,

First of all, thanks for your work HockeyKit, it is really useful! and well designed.

I have a _small_ feature suggestion / proposal, the main idea would be to use HockeyKit on AppStore too :

Why :
- Easier to set up / archive / deploy your app, with only one build config.
- If a beta tester installs accidentally an AppStore version, he would still have beta updates > no need to deploy two app identifiers with two apps installed on device, which is complex for everyone, especially testers.

How :
- Of course only beta users should get betas. (an HK server side UDID check could easily do the job)
- All users could even be notified of a new AppStore version, which could be great. (would require some server side work to declare current AppStore version)

Let me know what you think about this!

Vincent.

**Comment by DerAndereAndi** [comment]
Hi,

thanks for the suggestion, _but_ the idea isn't as _small_ as it seems :)

Regarding the _Whys_:
- where is the problem in setting up 2 build configs once per product? Two info.plist is basically all you need, and an AdHoc configuration is required anyhow
- I always recommend using a different bundle identifier for beta versions. Reasons are easy: app store variants are stable, some users will only use the beta version, others won't. And having 2 info.plist files also makes this very easy to handle

Now the _Hows_:
- The first point is not easy, since you may not send UDID from AppStore versions without asking the user if he complies
- Versioning of beta versions may not be identical to AppStore versions, which means you would have versions on the server without ipa files, so defined differently. lots of code changes

Additions:
- AppStore users don't like it if your app does frequent update checks if they cannot turn it off
- When using two bundle identifiers (as highly recommended), checking for appstore versions requires the server to be able to manage

I agree that notifying AppStore users of pending updates is a problem, that iOS currently has. I have lots of users of my own app who never ever upgraded. Mostly because they simply don't know how or why they should. Most of them are not familier with computers or software, so giving them a hint in general is a good thing. But with the current infrastructure this is not a small change on the server as I pointed out. We cannot take this up, we simply don't have the time and also the need to have this handled by the HockeyKit open sources server. You are free to fork and add it :)

**Comment by vguerci** [comment]
Will do. :)

I thought the UDID sending was implicit with Apple agreement.
Anyway an alternative could be a in app compiled check.
Using of course hashes of udid for paranoids sake ;)

Thanks for your feedback.
