### ISSUE TITLE
Feature Request: Stats and password protected server

### ISSUE THREAD

**Issue by jaltek** [bitstadium/HockeyKit#74]
Hi there,

is there any chance to run the stats function of the server component on a password protected (apache / .htaccess) server?

The initial installation of an application (by using safari) works fine with a password protection (apart from the fact, that the password dialogue pops up twice which is AFAIK an iOS problem) but there are no settings available reporting the "stats" to a password protected server yet, right?

Greetings and keep up the good work ;)

**Comment by DerAndereAndi** [comment]
Hi,

simply add another .htaccess to the stats directory which uses a different set of allowed users.

Andreas

**Comment by jaltek** [comment]
Hi Andreas,

maybe I was a bit unclear ;)

If the server is password protected, the iOS client is not able to send the stats to the server because there isn´t an option to set any login credentials yet, correct?

Greets Jan

**Comment by DerAndereAndi** [comment]
Hi Jan,

this is correct. And honestly, I don't you want to set credentials in the source, because everybody having the file could find those strings. Why not use the authentication feature instead? This will block the app for most users if they don't try hard-core cracking things.

Andreas

**Comment by jaltek** [comment]
Hi Andreas,

good hint, thank you. But IMHO this doesn't prevent a user for installing the app via Safari.

Correct me if I'm wrong but the stats are reported to the same URL (or directory) as the URL for installing the app via Safari, right? 
Example:
Beta URL: example.org/beta/com.example.myapp
Stats reported to: example.org/beta/com.example.myapp

So protecting this URL will also prevent the client for sending the stats or did I overlook something?

**Comment by DerAndereAndi** [comment]
Hi Jan,

the user will be able to install the app, yes, after re-signing it. But the app will present a lockup screen trying to authorize the usage which will be denied, since the users UDID is not present in your stats directories file. Every subsequent run will show the lock view, which is put on top of the UIWindow. There may be cases where this does not work, e.g. if a keyboard is shown right on startup or some other weird scenarios.

If you protect the main url via user & password, you will have to add that into the URL in your app like `http://user:password@myserver.com/beta/`. This is the main gate for everything, also receiving the stats, since checking for a new version and sending the stats is one single request.

Just to mention it, you could also use our hosted server at http://www.hockeyapp.net/ where all data is send via https and you can a private token for accessing your app. Uses the same client code etc.

**Comment by jaltek** [comment]
Hi Andreas,

thank you very much. I completely forgot the http://user:password@myserver.com variant but I have to agree with you - it isn't really safe. I will have a look at hockeyapp ;)

Thanks a lot again.
